[tool.poetry]
name = "endoreg-db"
version = "0.2.3"
description = "EndoReg Db Django App"
authors = ["Thomas J. Lux"]
license = "GNU3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "~4.2"
djangorestframework = "^3.14.0"
django-bootstrap5 = "^23.4"
tqdm = "^4.66.2"
pyyaml = "^6.0.1"
icecream = "^2.1.3"
pillow = "^10.2.0"
# opencv-python



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
